version: '3.9'

networks: 
    tig-net:
        driver: bridge

volumes:
    tig-data:

services:
    influxdb:
        image: influxdb:1.8.6
        container_name: influxdb
        ports:
            - 8086:8086
        environment:
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_DB: "iot"
            INFLUXDB_ADMIN_USER: "iotlnu"
            INFLUXDB_ADMIN_PASSWORD: "micropython"
            
            INFLUXDB_HTTP_HTTPS_ENABLED: "true"
            INFLUXDB_HTTP_HTTPS_CERTIFICATE: "/etc/certs/server-cert.pem"
            INFLUXDB_HTTP_HTTPS_PRIVATE_KEY: "/etc/certs/server-key.pem"
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/influxdb
            - ./certs:/etc/certs:ro
            #- ./influxdb.conf:/etc/influxdb/influxdb.conf

    grafana:
        image: grafana/grafana:8.0.5
        container_name: grafana
        ports: 
            - 3000:3000
        environment:
            GF_SECURITY_ADMIN_USER: "king"
            GF_SECURITY_ADMIN_PASSWORD: "arthur"
            GF_SERVER_ROOT_URL: "https://example.com"
            GF_SERVER_PROTOCOL: "https"
            GF_SERVER_CERT_FILE: "/etc/certs/server-cert.pem"
            GF_SERVER_CERT_KEY: "/etc/certs/server-key.pem"
        networks: 
            - tig-net
        volumes:
            - tig-data:/var/lib/grafana
            - ./certs:/etc/certs:ro
        restart: always        

    telegraf:
        image: telegraf:1.19.0
        depends_on: 
            - "influxdb"
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf
            - ./certs:/etc/certs:ro
        tty: true
        networks: 
            - tig-net
        privileged: true
